CREATE DATABASE IF NOT EXISTS medication_db;

USE medication_db;

CREATE TABLE IF NOT EXISTS medication_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  medicine_name VARCHAR(255) NOT NULL,
  breakfast INT NOT NULL DEFAULT 0,
  lunch INT NOT NULL DEFAULT 0,
  dinner INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 